version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: latest
  pre_build:
    commands:
      - npm install
      - dnf install -y xorg-x11-server-Xvfb gtk3-devel nss alsa-lib
  build:
    commands:
      - npm run testing
  post_build:
    commands:
      - aws s3 sync allure-report s3://s3-test-report/
      - aws s3 cp --recursive --acl public-read s3://s3-test-report/ s3://s3-test-report/
      - echo "The HTML report can be found here <http://s3-test-report.s3-website.us-east-2.amazonaws.com/> "
